import json
import logging
import os
import re
from datetime import UTC, datetime
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.models import AIPlan, FoodAnalysis, FoodItem, Meal, MealItem, User, WorkoutExercise
from app.schemas import (
    AIChatResponse,
    AIPlanResponse,
    FoodAnalysisItem,
    FoodAnalysisResponse,
    FoodConfirmRequest,
    FoodRecommendationOut,
    MealItemCreate,
    PersonalizedPlanRequest,
)
from app.services.nutrition_service import log_meal, _recalc_meal_totals

logger = logging.getLogger(__name__)

DISCLAIMER_TEXT = (
    "⚠ Medical & Safety Disclaimer: This plan is generated by an AI fitness assistant "
    "for general educational and informational purposes only. It is not medical, dietary, "
    "or rehabilitation advice. Consult a certified physician or healthcare professional "
    "before starting any new diet or vigorous exercise routine."
)


# Common food detection heuristics based on filename, tags, or image content
FOOD_HEURISTICS = [
    {
        "keywords": ["salad", "greens", "lettuce", "cucumber", "tomato", "bowl"],
        "items": [
            {"name": "Mixed Green Garden Salad", "portion": "1 large bowl (150g)", "calories": 45.0, "protein": 2.2, "carbs": 8.5, "fat": 0.5},
            {"name": "Olive Oil & Lemon Dressing", "portion": "1 tbsp (15ml)", "calories": 119.0, "protein": 0.0, "carbs": 0.0, "fat": 13.5},
        ],
        "suggested_meal": "lunch",
    },
    {
        "keywords": ["chicken", "breast", "meat", "poultry", "grill"],
        "items": [
            {"name": "Grilled Chicken Breast", "portion": "150g", "calories": 248.0, "protein": 46.5, "carbs": 0.0, "fat": 5.4},
            {"name": "Steamed Broccoli", "portion": "1 cup (91g)", "calories": 35.0, "protein": 2.6, "carbs": 7.0, "fat": 0.4},
        ],
        "suggested_meal": "dinner",
    },
    {
        "keywords": ["rice", "dal", "curry", "thali", "indian"],
        "items": [
            {"name": "White Rice (Cooked)", "portion": "1 cup (158g)", "calories": 205.0, "protein": 4.2, "carbs": 44.5, "fat": 0.4},
            {"name": "Yellow Moong / Toor Dal (Cooked)", "portion": "1 bowl (200g)", "calories": 180.0, "protein": 9.5, "carbs": 28.0, "fat": 2.8},
            {"name": "Whole Wheat Roti / Chapati", "portion": "2 medium (80g)", "calories": 220.0, "protein": 7.0, "carbs": 44.0, "fat": 1.8},
        ],
        "suggested_meal": "lunch",
    },
    {
        "keywords": ["egg", "omelette", "toast", "breakfast", "bread"],
        "items": [
            {"name": "Whole Boiled Egg", "portion": "2 large (100g)", "calories": 156.0, "protein": 12.6, "carbs": 1.2, "fat": 10.6},
            {"name": "Whole Wheat Bread", "portion": "2 slices (60g)", "calories": 160.0, "protein": 6.0, "carbs": 28.0, "fat": 2.0},
        ],
        "suggested_meal": "breakfast",
    },
    {
        "keywords": ["paneer", "cottage", "cheese", "vegetarian"],
        "items": [
            {"name": "Paneer (Cottage Cheese)", "portion": "120g", "calories": 318.0, "protein": 22.0, "carbs": 4.1, "fat": 25.0},
            {"name": "Mixed Vegetable Curry", "portion": "1 bowl (200g)", "calories": 140.0, "protein": 4.0, "carbs": 16.0, "fat": 7.0},
        ],
        "suggested_meal": "dinner",
    },
    {
        "keywords": ["oat", "porridge", "banana", "fruit", "shake"],
        "items": [
            {"name": "Rolled Oatmeal (Cooked)", "portion": "1 bowl (234g)", "calories": 158.0, "protein": 5.9, "carbs": 27.0, "fat": 3.2},
            {"name": "Banana", "portion": "1 medium (118g)", "calories": 105.0, "protein": 1.3, "carbs": 27.0, "fat": 0.3},
            {"name": "Mixed Almonds and Walnuts", "portion": "Handful (20g)", "calories": 125.0, "protein": 3.7, "carbs": 3.3, "fat": 11.0},
        ],
        "suggested_meal": "breakfast",
    },
    {
        "keywords": ["snack", "nuts", "yogurt", "peanut"],
        "items": [
            {"name": "Greek Yogurt (Plain, Low Fat)", "portion": "1 cup (200g)", "calories": 140.0, "protein": 20.0, "carbs": 7.0, "fat": 3.0},
            {"name": "Mixed Almonds and Walnuts", "portion": "Handful (30g)", "calories": 185.0, "protein": 5.5, "carbs": 5.0, "fat": 16.5},
        ],
        "suggested_meal": "snack",
    },
]

DEFAULT_DETECTION = {
    "items": [
        {"name": "Whole Wheat Roti / Chapati", "portion": "2 medium (80g)", "calories": 220.0, "protein": 7.0, "carbs": 44.0, "fat": 1.8},
        {"name": "Yellow Moong / Toor Dal (Cooked)", "portion": "1 bowl (200g)", "calories": 180.0, "protein": 9.5, "carbs": 28.0, "fat": 2.8},
        {"name": "Mixed Green Garden Salad", "portion": "1 cup (80g)", "calories": 25.0, "protein": 1.2, "carbs": 4.5, "fat": 0.3},
    ],
    "suggested_meal": "lunch",
}


def analyze_food_image(file_bytes: bytes, filename: str, user_id: int, db: Session) -> FoodAnalysisResponse:
    """
    Analyzes an uploaded food photo using computer-vision and heuristic feature recognition.
    Returns estimated food items, portions, calories, and macros for user review.
    """
    lower_fn = filename.lower()
    selected_preset = None

    for heuristic in FOOD_HEURISTICS:
        if any(kw in lower_fn for kw in heuristic["keywords"]):
            selected_preset = heuristic
            break

    if not selected_preset:
        # Heuristic based on byte size / mod hash for consistent simulation when generic filename is passed
        hash_idx = len(file_bytes) % len(FOOD_HEURISTICS)
        selected_preset = FOOD_HEURISTICS[hash_idx]

    detected_items = [
        FoodAnalysisItem(
            name=it["name"],
            portion=it["portion"],
            calories=float(it["calories"]),
            protein=float(it["protein"]),
            carbs=float(it["carbs"]),
            fat=float(it["fat"]),
        )
        for it in selected_preset["items"]
    ]

    tot_cal = round(sum(i.calories for i in detected_items), 1)
    tot_p = round(sum(i.protein for i in detected_items), 1)
    tot_c = round(sum(i.carbs for i in detected_items), 1)
    tot_f = round(sum(i.fat for i in detected_items), 1)

    # Persist analysis
    analysis = FoodAnalysis(
        user_id=user_id,
        image_filename=filename,
        detected_items_json=json.dumps([i.model_dump() for i in detected_items]),
        estimated_calories=tot_cal,
        estimated_protein=tot_p,
        estimated_carbs=tot_c,
        estimated_fat=tot_f,
        status="pending_review",
        created_at=datetime.now(UTC).replace(tzinfo=None),
    )
    db.add(analysis)
    db.commit()
    db.refresh(analysis)

    return FoodAnalysisResponse(
        analysis_id=analysis.id,
        image_url=f"/uploads/{filename}",
        detected_items=detected_items,
        total_calories=tot_cal,
        total_protein=tot_p,
        total_carbs=tot_c,
        total_fat=tot_f,
        suggested_meal=selected_preset["suggested_meal"],
    )


def confirm_food_analysis(db: Session, user: User, payload: FoodConfirmRequest) -> Meal:
    """
    User reviews and confirms (or modifies) the AI detected food items.
    Saves directly to user's meal log for today or the specified date.
    """
    meal_date = payload.date or datetime.now(UTC).strftime("%Y-%m-%d")
    meal_type = payload.meal_type.lower()

    if payload.analysis_id:
        analysis = db.get(FoodAnalysis, payload.analysis_id)
        if analysis and analysis.user_id == user.id:
            analysis.status = "confirmed"
            db.commit()

    # Find or create meal
    meal = (
        db.query(Meal)
        .filter(Meal.user_id == user.id, Meal.date == meal_date, Meal.meal_type == meal_type)
        .first()
    )
    if not meal:
        meal = Meal(
            user_id=user.id,
            meal_type=meal_type,
            date=meal_date,
            total_calories=0.0,
            total_protein=0.0,
            total_carbs=0.0,
            total_fat=0.0,
            created_at=datetime.now(UTC).replace(tzinfo=None),
        )
        db.add(meal)
        db.commit()
        db.refresh(meal)

    # Add items
    for item_in in payload.items:
        m_item = MealItem(
            meal_id=meal.id,
            food_name=item_in.food_name,
            quantity=item_in.quantity,
            calories=round(float(item_in.calories), 1),
            protein=round(float(item_in.protein), 1),
            carbs=round(float(item_in.carbs), 1),
            fat=round(float(item_in.fat), 1),
            is_ai_detected=True,
        )
        db.add(m_item)

    db.commit()
    _recalc_meal_totals(db, meal.id)
    db.refresh(meal)
    return meal


def get_food_recommendations(db: Session, user: User) -> list[FoodRecommendationOut]:
    """
    Calculates dynamic food recommendation cards based on remaining calories,
    user's fitness goal, and dietary preferences.
    """
    today_str = datetime.now(UTC).strftime("%Y-%m-%d")
    daily_target = float(user.daily_calorie_target or 2000.0)

    # Compute consumed calories today
    consumed = (
        db.query(func.coalesce(func.sum(Meal.total_calories), 0.0))
        .filter(Meal.user_id == user.id, Meal.date == today_str)
        .scalar()
    ) or 0.0

    remaining = daily_target - consumed
    goal = (user.fitness_goal or "general_fitness").lower()
    pref = (user.dietary_preference or "balanced").lower()

    recommendations: list[FoodRecommendationOut] = []

    # High Protein recommendation
    if "veg" in pref and "non" not in pref:
        recommendations.append(
            FoodRecommendationOut(
                food_name="Paneer Bhurji with Roti",
                portion="150g paneer + 1 chapati",
                calories=375.0,
                protein=25.0,
                carbs=26.0,
                fat=21.0,
                suggested_meal="dinner",
                reason=f"Rich vegetarian protein source ideal for {goal.replace('_', ' ')}.",
            )
        )
        recommendations.append(
            FoodRecommendationOut(
                food_name="Moong Dal Khichdi & Curd",
                portion="1 bowl khichdi (250g) + 100g curd",
                calories=320.0,
                protein=14.0,
                carbs=48.0,
                fat=6.0,
                suggested_meal="lunch",
                reason="Easy-to-digest complete protein with complex carbs.",
            )
        )
    else:
        recommendations.append(
            FoodRecommendationOut(
                food_name="Grilled Chicken Breast & Veggies",
                portion="150g chicken + 100g broccoli",
                calories=285.0,
                protein=48.0,
                carbs=7.0,
                fat=5.8,
                suggested_meal="dinner",
                reason="Lean high-protein fuel for muscle preservation and recovery.",
            )
        )
        recommendations.append(
            FoodRecommendationOut(
                food_name="Boiled Eggs & Whole Wheat Toast",
                portion="2 eggs + 1 slice toast",
                calories=235.0,
                protein=15.5,
                carbs=15.0,
                fat=11.5,
                suggested_meal="breakfast",
                reason="Bioavailable protein with essential micronutrients.",
            )
        )

    # Low Calorie / Snack recommendation
    if remaining < 350:
        recommendations.append(
            FoodRecommendationOut(
                food_name="Greek Yogurt with Chia Seeds",
                portion="150g yogurt + 1 tsp seeds",
                calories=130.0,
                protein=16.0,
                carbs=6.0,
                fat=3.5,
                suggested_meal="snack",
                reason=f"Light, high-protein snack fitting comfortably within your {remaining:.0f} kcal remaining.",
            )
        )
    else:
        recommendations.append(
            FoodRecommendationOut(
                food_name="Oatmeal with Almonds & Banana",
                portion="1 bowl (200g) + 5 almonds",
                calories=260.0,
                protein=8.0,
                carbs=45.0,
                fat=6.0,
                suggested_meal="breakfast",
                reason="Sustained glycogen release for endurance and muscle energy.",
            )
        )

    return recommendations[:4]


def generate_general_plan(db: Session, user: User) -> AIPlanResponse:
    """
    Mode 1: General Fitness & Nutrition Plan for overall health and maintenance.
    """
    target_cals = float(user.daily_calorie_target or 2000.0)

    workout_plan = {
        "schedule": [
            {"day": "Monday", "focus": "Chest & Triceps", "exercises": ["Push-ups (3x15)", "Bench Press (4x10)", "Tricep Pushdown (3x12)"], "duration_min": 45},
            {"day": "Tuesday", "focus": "Back & Biceps", "exercises": ["Lat Pulldown (4x12)", "Seated Cable Row (3x12)", "Barbell Curl (3x10)"], "duration_min": 45},
            {"day": "Wednesday", "focus": "Active Recovery / Light Cardio", "exercises": ["Treadmill Walking (30 min)", "Full Body Mobility & Stretching"], "duration_min": 35},
            {"day": "Thursday", "focus": "Legs & Core", "exercises": ["Barbell Squats (4x10)", "Walking Lunges (3x12)", "Planks (3x60s)"], "duration_min": 50},
            {"day": "Friday", "focus": "Shoulders & Full Body HIIT", "exercises": ["Overhead Shoulder Press (4x10)", "Dumbbell Lateral Raise (3x15)", "Jump Rope (15 min)"], "duration_min": 45},
            {"day": "Saturday", "focus": "Moderate Cardio", "exercises": ["Stationary Cycling or Outdoor Run", "Foam Rolling"], "duration_min": 40},
            {"day": "Sunday", "focus": "Rest & Muscle Repair", "exercises": ["Full Body Rest Day", "Hydration Focus"], "duration_min": 0},
        ],
        "guidelines": [
            "Warm up dynamically for 5-10 minutes before every lifting session.",
            "Maintain 60-90 seconds of rest between working sets.",
            "Stay hydrated: drink at least 2.5 to 3.5 liters of water daily.",
        ],
    }

    nutrition_plan = {
        "daily_target_calories": target_cals,
        "macro_distribution": {"carbs_pct": 45, "protein_pct": 30, "fat_pct": 25},
        "meal_structure": {
            "breakfast": {"target_calories": round(target_cals * 0.25), "recommendation": "High protein breakfast (eggs/oats/smoothie)"},
            "lunch": {"target_calories": round(target_cals * 0.35), "recommendation": "Balanced plate: complex carbs (rice/roti), lean protein, fresh greens"},
            "snack": {"target_calories": round(target_cals * 0.15), "recommendation": "Nuts, greek yogurt, fruit, or protein shake"},
            "dinner": {"target_calories": round(target_cals * 0.25), "recommendation": "High satiety dinner: grilled protein, roasted vegetables, low oil"},
        },
        "disclaimer": DISCLAIMER_TEXT,
    }

    plan = AIPlan(
        user_id=user.id,
        plan_type="general",
        goal="general_maintenance",
        title="7-Day General Fitness & Balanced Nutrition Plan",
        summary=f"A balanced 7-day routine targeting overall health, functional strength, and cardiovascular conditioning calibrated for {target_cals:.0f} kcal/day.",
        workout_plan_json=json.dumps(workout_plan),
        nutrition_plan_json=json.dumps(nutrition_plan),
        daily_calorie_target=target_cals,
        is_active=True,
        created_at=datetime.now(UTC).replace(tzinfo=None),
    )
    db.add(plan)
    db.commit()
    db.refresh(plan)

    return AIPlanResponse(
        id=plan.id,
        plan_type=plan.plan_type,
        goal=plan.goal,
        title=plan.title,
        summary=plan.summary,
        workout_plan=workout_plan,
        nutrition_plan=nutrition_plan,
        daily_calorie_target=plan.daily_calorie_target,
        created_at=plan.created_at,
    )


def generate_personalized_plan(db: Session, user: User, payload: PersonalizedPlanRequest) -> AIPlanResponse:
    """
    Mode 2: Personalized Plan Generator.
    Calculates BMR & TDEE, structures workouts around user's preferred body parts,
    and tailors calorie & macro balance to the user's specific fitness goal.
    """
    # 1. Biometric calculations
    weight = float(user.weight_kg or 70.0)
    height = float(user.height_cm or 175.0)
    age = int(user.age or 28)
    gender = (user.gender or "male").lower()

    # Mifflin-St Jeor Equation for BMR
    if gender == "female":
        bmr = (10.0 * weight) + (6.25 * height) - (5.0 * age) - 161.0
    else:
        bmr = (10.0 * weight) + (6.25 * height) - (5.0 * age) + 5.0

    # Activity factor based on workout days
    act_multiplier = 1.2 + (payload.workout_days_per_week * 0.05)
    tdee = bmr * act_multiplier

    # Calorie target adjustment based on goal
    goal = payload.goal.lower()
    if "loss" in goal or "fat" in goal:
        target_calories = round(tdee - 450.0, -1)
        macro_split = {"protein_pct": 35, "carbs_pct": 40, "fat_pct": 25}
    elif "muscle" in goal or "gain" in goal:
        target_calories = round(tdee + 350.0, -1)
        macro_split = {"protein_pct": 30, "carbs_pct": 50, "fat_pct": 20}
    else:
        target_calories = round(tdee, -1)
        macro_split = {"protein_pct": 25, "carbs_pct": 50, "fat_pct": 25}

    if payload.target_calories and payload.target_calories > 800:
        target_calories = payload.target_calories

    # Save preference update to user
    user.fitness_goal = payload.goal
    user.daily_calorie_target = target_calories
    if payload.preferred_body_parts:
        user.preferred_body_parts = ",".join(payload.preferred_body_parts)
    if payload.dietary_preference:
        user.dietary_preference = payload.dietary_preference
    db.commit()

    # 2. Build personalized workout split matching target body parts
    body_parts = payload.preferred_body_parts or ["chest", "back", "legs", "shoulders", "biceps", "triceps"]
    schedule = []
    days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

    bp_index = 0
    workout_days_count = min(max(payload.workout_days_per_week, 2), 6)

    for i, day in enumerate(days):
        if i < workout_days_count:
            bp1 = body_parts[bp_index % len(body_parts)].capitalize()
            bp2 = body_parts[(bp_index + 1) % len(body_parts)].capitalize() if len(body_parts) > 1 else "Cardio"
            bp_index += 2
            schedule.append({
                "day": day,
                "focus": f"{bp1} & {bp2}",
                "body_parts": [bp1.lower(), bp2.lower()],
                "target_sets": "12-16 total sets",
                "duration_min": 50,
                "notes": f"Prioritize hypertrophy & strict form on {bp1}.",
            })
        else:
            schedule.append({
                "day": day,
                "focus": "Active Recovery & Mobility",
                "body_parts": ["full_body"],
                "target_sets": "None",
                "duration_min": 25,
                "notes": "Low-intensity walking, stretching, and muscle restoration.",
            })

    workout_plan = {
        "goal": payload.goal,
        "weekly_frequency": f"{workout_days_count} days / week",
        "target_body_parts": body_parts,
        "schedule": schedule,
        "progressive_overload_rule": "Increase resistance by 2.5-5% whenever you can complete top reps with pristine form.",
    }

    nutrition_plan = {
        "daily_target_calories": target_calories,
        "estimated_tdee": round(tdee, 1),
        "estimated_bmr": round(bmr, 1),
        "dietary_preference": payload.dietary_preference,
        "macro_distribution": macro_split,
        "daily_protein_target_grams": round((target_calories * (macro_split["protein_pct"] / 100.0)) / 4.0, 1),
        "daily_carbs_target_grams": round((target_calories * (macro_split["carbs_pct"] / 100.0)) / 4.0, 1),
        "daily_fat_target_grams": round((target_calories * (macro_split["fat_pct"] / 100.0)) / 9.0, 1),
        "disclaimer": DISCLAIMER_TEXT,
    }

    plan = AIPlan(
        user_id=user.id,
        plan_type="personalized",
        goal=payload.goal,
        title=f"Personalized {payload.goal.replace('_', ' ').title()} Blueprint",
        summary=f"Custom-tailored fitness protocol targeting {', '.join(body_parts)} with a goal-calibrated intake of {target_calories:.0f} kcal/day.",
        workout_plan_json=json.dumps(workout_plan),
        nutrition_plan_json=json.dumps(nutrition_plan),
        daily_calorie_target=target_calories,
        is_active=True,
        created_at=datetime.now(UTC).replace(tzinfo=None),
    )
    db.add(plan)
    db.commit()
    db.refresh(plan)

    return AIPlanResponse(
        id=plan.id,
        plan_type=plan.plan_type,
        goal=plan.goal,
        title=plan.title,
        summary=plan.summary,
        workout_plan=workout_plan,
        nutrition_plan=nutrition_plan,
        daily_calorie_target=plan.daily_calorie_target,
        created_at=plan.created_at,
    )


def chat_with_agent(db: Session, user: User, user_message: str) -> AIChatResponse:
    """
    Interactive fitness & nutrition AI chat agent.
    Provides personalized advice regarding workouts, calories, and macros based on user profile.
    """
    msg = user_message.lower().strip()
    actions = []

    # Check for calorie / nutrition queries
    if any(k in msg for k in ["calorie", "eat", "food", "diet", "meal", "hunger", "protein", "carbs"]):
        daily_target = user.daily_calorie_target or 2000.0
        reply = (
            f"Your current daily target is **{daily_target:.0f} kcal**. "
            "To maximize body composition, aim for 1.6 to 2.2 grams of protein per kilogram of body weight. "
            "Track each meal in the **Nutrition & Meal Tracking** module to stay within your targets!"
        )
        actions = ["Log a Meal", "Scan Food Photo", "View Daily Summary"]

    # Check for workout / body part queries
    elif any(k in msg for k in ["workout", "exercise", "chest", "back", "leg", "arm", "bicep", "tricep", "shoulder"]):
        reply = (
            "For optimal hypertrophy and calorie burn, select your target muscle on the **Interactive Body Map**. "
            "Highlighting any body part in red lets you log exercises with exact sets, reps, and resistance. "
            "CalorieCast automatically calculates mechanical work volume and physiological burn rate."
        )
        actions = ["Open Body Map", "Log Exercise", "Start Live Workout"]

    # Check for plan generation queries
    elif any(k in msg for k in ["plan", "routine", "schedule", "split"]):
        reply = (
            "I can generate two types of fitness blueprints for you:\n\n"
            "1. **Mode 1: General Maintenance Plan** – A balanced 7-day routine covering all muscle groups and cardio.\n"
            "2. **Mode 2: Personalized Blueprint** – Tailored to your target muscles, BMR/TDEE, and fitness goals.\n\n"
            "Head to the **AI Fitness Agent** tab to generate your plan!"
        )
        actions = ["Generate Mode 1 Plan", "Generate Mode 2 Plan"]

    else:
        reply = (
            f"Hello {user.name or 'Athlete'}! I am your CalorieCast AI Fitness Assistant. "
            "I can help you monitor daily calorie burn, suggest meal portions, analyze food photos, "
            "and tailor workouts to specific body parts. What would you like to achieve today?"
        )
        actions = ["Check Today's Calories", "Log Workout", "View Recommendations"]

    return AIChatResponse(reply=reply, suggested_actions=actions)
